# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-18 12:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.BooleanField(default=False)),
                ('hidden_result', models.BooleanField()),
                ('comment', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CheckGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CheckTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=250)),
                ('check_group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitytask.CheckGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (
                ('all_companies', 'Can view all companies'), ('current_companies', 'Can view current companies')),
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
                ('checkgroup',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitytask.CheckGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_all', 'view_all'), ('view_current', 'view_current')),
            },
        ),
        migrations.AddField(
            model_name='checkgroup',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitytask.Client'),
        ),
        migrations.AddField(
            model_name='check',
            name='check_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitytask.CheckTask'),
        ),
        migrations.AddField(
            model_name='check',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
